[Main]
RealAppId=2753970
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
DeviceIdAuth=true

[Hashes]
0=21a834c7f410b1ef476b9aade42facc9212236842713b309c1e424893a36b2aed3a78f6ec9c5ef9531a1937f66c81aa198117d9888d7f7cd60c302977824d1d9
