[Main]
RealAppId=239140
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
BasicProfile=true
FriendsList=true
Presence=true

[DLC]
302100=Dying Light - Be the Zombie
302101=Dying Light - Cuisine & Cargo
302102=Dying Light - Punk Queen Weapon Pack
302103=Dying Light - Buzz Killer Weapon Pack
325710=Dying Light - Night Club Weapon Pack
325711=Dying Light - The Lacerator Weapon Pack
325712=Dying Light - The Constable Weapon Pack
325713=Dying Light - Wrench Kiss Weapon Pack
325714=Dying Light - Ninja Outfit
325715=Dying Light - Urban Explorer Outfit
325716=Dying Light - Special Agent Outfit
325717=Dying Light - Techland Outfit
325720=Dying Light - Alienware Outfit
325721=Dying Light - Nvidia Outfit
325722=Dying Light - Razer Outfit
325723=Dying Light - The Bozak Horde
325724=Dying Light - The Following
335810=Dying Light Season Pass
347090=Dying Light Ultimate Survivor Bundle
412920=Dying Light - Custom Maps
415360=Dying Light: Razer Nabu Outfit
415370=Dying Light - Custom Maps 2
435110=Dying Light: Outfit and Livery 1
435111=Dying Light- Crash Test Skin Pack
436080=Dying Light- Harran Ranger Bundle
436081=Dying Light- Gun Psycho Bundle
436082=Dying Light- Volatile Hunter Bundle
436083=Dying Light: CD-Action Anniversary Pack
675860=Dying Light - Harran Military Rifle
748340=Dying Light - White Death Bundle
748341=Dying Light - Vintage Gunslinger Bundle
798541=Dying Light 3D Printer Models
798542=Dying Light Collector’s Artbook
798543=Dying Light Wallpaper Pack
1034630=Dying Light Book
1112520=Dying Light - Rais Elite Bundle
1112521=Dying Light - Godfather Bundle
1174580=Dying Light - Harran Inmate Bundle
1174581=Dying Light - Left 4 Dead 2 Weapon Pack
1177880=Dying Light - Retrowave Bundle
1184350=Dying Light - SHU Warrior Bundle
1184351=Dying Light - Chivalry Weapon Pack
1241570=Dying Light - 5th Anniversary Bundle
1272090=Dying Light - Unturned Weapon Pack
1300710=Dying Light - Hellraid
1336220=Dying Light - Hellraid Beta
1354960=Dying Light - Volkan Combat Armor Bundle
1454750=Dying Light - L4D2 Bill & Gnome Chompski Pack
1468290=Dying Light - Classified Operation Bundle
1498210=Dying Light - Viking: Raider of Harran Bundle
1524890=Dying Light - Ox Warrior Bundle
1543420=Dying Light - Harran Tactical Unit Bundle
1599030=Dying Light - Rust Weapon Pack
1647900=Dying Light - Savvy Gamer Bundle
1702060=Dying Light - Astronaut Bundle
1762700=Dying Light - Van Crane Bundle
1822810=Dying Light - Snow Ops Bundle
1935540=Dying Light - Dieselpunk Bundle
3607960=SteamDB Unknown App 3607960
3454290=Dying Light - 10th Anniversary Bundle
2971380=Dying Light - Standard To Definitive Upgrade
2971370=Dying Light - Standard To Enhanced Upgrade

[Hashes]
0=a509d41a33341b1fcb7a0640f25c06aaf84f58616f01a3f1163b7b694c8549f4710f57daeed1723170ceb97c0ac173daf9b9631feb5ca47e9fd1a0a771696f3b
