[Main]
RealAppId=534380
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
DeviceIdAuth=true

[DLC]
3833090=Dying Light 2 - 1500 DLP One-off Offer
3818860=Dying Light 2: Stay Human - 2300 DLP For Summer Edition
3453200=Dying Light 2 Stay Human: G.R.E. Hazmat Bundle
2456710=Dying Light 2 - Hakon Bundle
2400900=Dying Light 2 Stay Human: The Walking Dead Bundle
2370710=Dying Light 2 - Nightrunner Bundle
2370700=Dying Light 2 - Post-apo Bundle
2370480=Dying Light 2 - Gunslinger Bundle
2370460=Dying Light 2 - Rahim Bundle
2330980=Dying Light 2 - Chicken Bundle
2269820=Dying Light 2 - Brecken Skin Bundle
2269810=Dying Light 2 - Rais Skin Bundle
2217480=Dying Light 2 - Developer Tools
2210190=Dying Light 2 - Nutcracker Bundle
2156750=Dying Light 2 - Dying Laugh Bundle
2108090=Dying Light 2 - The Aristocrat Pack
1937531=Dying Light 2 - Ultimate Upgrade
1937530=Dying Light 2 - Deluxe Upgrade
1888510=Dying Light 2 - Soundtrack
1864260=Dying Light 2 - Survivor 03
1864250=Dying Light 2 - Survivor 02
1864240=Dying Light 2 - Survivor 01
1864230=Dying Light 2 - Peacekeeper 03
1864200=Dying Light 2 - Peacekeeper 02
1864100=Dying Light 2 - Peacekeeper 01
1537625=SteamDB Unknown App 1537625 (data_dlc2)
1537624=Dying Light 2 Stay Human: Bloody Ties
1537623=Dying Light 2 - Pre-order pack
1537622=Dying Light 2 - Artbook
1537621=Dying Light 2 - Ultimate pack
1537620=Dying Light 2 - Deluxe Pack
1263580=SteamDB Unknown App 1263580 (DEV_WINDOWS)

[Hashes]
0=d84cf21f9fbe5c6d521749e28ebaeceae55d1ce0117f6e512f02afbdbcedfa10b918ce1ca21c412a393224c0601f3c35152c524a5d6026d90a001d647c260c63